baseURL = 'https://blog.shrivarshapoojary.in/'

languageCode = 'en-us'
title = 'The Compiler Journal'
theme = "paper"

[pagination]
  pagerSize = 3

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  # Configure main sections to display on homepage
  mainSections = ["posts"]
  
  # color style
  color = 'linen'

  # social links
  linkedin = 'shrivarsha-poojary-960691249/'             
  github = 'shrivarshapoojari'

  # profile
  avatar = 'shrivarshapoojary8095@gmail.com'                 
  name = 'Shrivarsha Poojary'

  # features
  math = true