baseURL = 'https://shrivarshapoojari.github.io/'
languageCode = 'en-us'
title = 'The Compiler Journal'
theme = "paper"

[pagination]
  pagerSize = 3

[caches]
  [caches.images]
    dir = ':cacheDir/images'

     

[params]
  # color style
  color = 'linen'                          

 
 
 
  linkedin = 'https://www.linkedin.com/in/shrivarsha-poojary-960691249/'             
  github = 'https://github.com/shrivarshapoojari'  
                                
 


  avatar = 'shrivarshapoojary8095@gmail.com'                 
  name = 'Shrivarsha Poojary'
  

 math = true   
 
